package org.zerionproject.core.api.crypto;

public enum DecryptionResult {

	SUCCESS,

	INVALID_CIPHERTEXT,

	KEY_STRENGTHENER_ERROR,

	INVALID_PASSWORD,
	KEY_REPLACEMENT_FAILED,
	KEY_REPLACEMENT_UNCERTAIN,
	KEY_FILES_DAMAGED
}
