package org.zerionproject.wire;

public interface ZwfConstants {

	int WIRE_VERSION = 1;

	int FRAME_LENGTH = 4096;

	int MAC_LENGTH = 16;

	int NONCE_LENGTH = 24;

	int FRAME_HEADER_PLAINTEXT_LENGTH = 4;

	int FRAME_HEADER_LENGTH = FRAME_HEADER_PLAINTEXT_LENGTH + MAC_LENGTH;

	int TAG_LENGTH = 16;

	int STREAM_ID_LENGTH = 8;

	int REPLAY_WINDOW_SIZE = 256;

	int STREAM_HEADER_PLAINTEXT_LENGTH = 2 + STREAM_ID_LENGTH;

	int STREAM_HEADER_LENGTH =
			NONCE_LENGTH + STREAM_HEADER_PLAINTEXT_LENGTH + MAC_LENGTH;

	int SEGMENT_FRAME_HEADER = 0;
	int SEGMENT_MODE3FULL_HEADER = 1;
	int SEGMENT_BODY = 2;

	int DIRECTION_SEND = 0;
	int DIRECTION_RECV = 1;
}
