package org.zerionproject.core.db;

import org.zerionproject.core.api.crypto.SecretKey;
import org.zerionproject.core.api.db.DatabaseConfig;
import org.zerionproject.core.api.db.DbClosedException;
import org.zerionproject.core.api.db.DbException;
import org.zerionproject.core.api.db.MigrationListener;
import org.zerionproject.core.api.sync.MessageFactory;
import org.zerionproject.core.api.system.Clock;
import org.zerionproject.core.util.StringUtils;
import org.briarproject.nullsafety.NotNullByDefault;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.annotation.Nullable;
import javax.inject.Inject;
import static org.zerionproject.core.db.JdbcUtils.tryToClose;
import static org.zerionproject.core.util.IoUtils.isNonEmptyDirectory;

@NotNullByDefault
class HyperSqlDatabase extends JdbcDatabase {
	private static final String HASH_TYPE = "BINARY(32)";
	private static final String SECRET_TYPE = "BINARY(32)";
	private static final String BINARY_TYPE = "BINARY";
	private static final String COUNTER_TYPE =
			"INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1)";
	private static final String STRING_TYPE = "VARCHAR";
	private static final DatabaseTypes dbTypes = new DatabaseTypes(HASH_TYPE,
			SECRET_TYPE, BINARY_TYPE, COUNTER_TYPE, STRING_TYPE);

	private final DatabaseConfig config;
	private final String url;

	@Nullable
	private volatile SecretKey key = null;
	private volatile boolean opened = false;
	private final Object closeLock = new Object();

	@Inject
	HyperSqlDatabase(DatabaseConfig config, MessageFactory messageFactory,
			Clock clock) {
		super(dbTypes, messageFactory, clock);
		this.config = config;
		File dir = config.getDatabaseDirectory();
		String path = new File(dir, "db").getAbsolutePath();
		url = "jdbc:hsqldb:file:" + path
				+ ";sql.enforce_size=false;allow_empty_batch=true"
				+ ";encrypt_lobs=true;crypt_type=AES";
	}

	@Override
	public boolean open(SecretKey key, @Nullable MigrationListener listener)
			throws DbException {
		this.key = new SecretKey(key.getBytes().clone());
		this.opened = false;
		File dir = config.getDatabaseDirectory();
		boolean reopen = isNonEmptyDirectory(dir);
		super.open("org.hsqldb.jdbc.JDBCDriver", reopen, this.key, listener);
		opened = true;
		return reopen;
	}

	/**
	 * Closes the database and clears the clean-shutdown flag while the private
	 * key copy is still valid, then zeroes that copy. The key copied at open
	 * is owned here, so a caller clearing its own key object before close
	 * cannot prevent the final dirty-flag write. Idempotent: a second close,
	 * or a close after a failed open, only clears the key and returns.
	 */
	@Override
	public void close() throws DbException {
		synchronized (closeLock) {
			if (key == null) return;
			if (!opened) {
				clearKey();
				return;
			}
			Connection c = null;
			Statement s = null;
			try {
				closeAllConnections();
				c = createConnection();
				setDirty(c, false);
				s = c.createStatement();
				s.executeQuery("SHUTDOWN COMPACT");
				s.close();
				c.close();
			} catch (SQLException e) {
				tryToClose(s);
				tryToClose(c);
				throw new DbException(e);
			} finally {
				opened = false;
				clearKey();
			}
		}
	}

	private void clearKey() {
		SecretKey k = key;
		key = null;
		if (k != null) k.clear();
	}

	/** Whether a private key copy is still held; for tests only. */
	boolean holdsKey() {
		return key != null;
	}

	@Override
	protected Connection createConnection() throws DbException, SQLException {
		SecretKey key = this.key;
		if (key == null) throw new DbClosedException();
		String hex = StringUtils.toHexString(key.getBytes());
		return DriverManager.getConnection(url + ";crypt_key=" + hex);
	}

	@Override
	protected void compactAndClose() throws DbException {
		Connection c = null;
		Statement s = null;
		try {
			closeAllConnections();
			c = createConnection();
			s = c.createStatement();
			s.executeQuery("SHUTDOWN COMPACT");
			s.close();
			c.close();
		} catch (SQLException e) {
			tryToClose(s);
			tryToClose(c);
			throw new DbException(e);
		}
	}
}
