package org.briarproject.briar.conversation.voice;

import org.briarproject.bramble.api.crypto.SecretKey;
import org.briarproject.bramble.api.plugin.TransportId;
import org.briarproject.bramble.api.rendezvous.KeyMaterialSource;
import org.briarproject.nullsafety.NotNullByDefault;

/**
 * Provides cryptographic operations for voice calls, including generating
 * per-call keys for creating Tor hidden services.
 * <p>
 * Each voice call uses a unique ephemeral key generated by the caller,
 * providing Perfect Forward Secrecy - if a call key is compromised,
 * past and future calls remain secure.
 */
@NotNullByDefault
public interface VoiceCallCrypto {

	/**
	 * Generates a new random voice call key.
	 * <p>
	 * The caller generates this key and sends it (encoded) to the callee
	 * in the CALL_OFFER message. Both parties then use the same key.
	 *
	 * @return A new random secret key for this call
	 */
	SecretKey generateVoiceCallKey();

	/**
	 * Encodes a voice call key to a string for transmission in signaling.
	 * <p>
	 * This produces a base64-encoded representation of the key that can
	 * be safely included in the CALL_OFFER message.
	 *
	 * @param key The voice call key to encode
	 * @return Base64-encoded key string
	 */
	String encodeVoiceCallKey(SecretKey key);

	/**
	 * Decodes a voice call key from a string received in signaling.
	 * <p>
	 * This decodes the base64-encoded key received in the CALL_OFFER.
	 *
	 * @param encoded The base64-encoded key string
	 * @return The decoded secret key
	 * @throws IllegalArgumentException if the encoded string is invalid
	 */
	SecretKey decodeVoiceCallKey(String encoded);

	/**
	 * Creates a KeyMaterialSource for use with createRendezvousEndpoint().
	 * <p>
	 * This source generates deterministic key material for creating
	 * Tor hidden services. Both Alice and Bob derive the same keys
	 * from the call key, but use them differently (Alice for her
	 * hidden service, Bob for his).
	 *
	 * @param voiceCallKey The key derived from deriveVoiceCallKey()
	 * @param transportId The transport ID (typically TorConstants.ID)
	 * @return A KeyMaterialSource that can be used to create rendezvous endpoints
	 */
	KeyMaterialSource createKeyMaterialSource(SecretKey voiceCallKey,
			TransportId transportId);

	/**
	 * Computes the local onion address from key material.
	 * <p>
	 * This derives the .onion address where THIS party's hidden service
	 * will listen. The same logic is used internally by TorPlugin when
	 * creating the rendezvous endpoint.
	 * <p>
	 * For the callee (alice=false): Returns Bob's onion (where Bob listens)
	 * For the caller (alice=true): Returns Alice's onion (where Alice listens)
	 *
	 * @param keyMaterial The KeyMaterialSource created from the voice call key
	 * @param alice True if this is Alice (caller), false if Bob (callee)
	 * @return The .onion address (without .onion suffix) where the hidden service listens
	 */
	String getLocalOnion(KeyMaterialSource keyMaterial, boolean alice);

	/**
	 * Derives symmetric keys for audio frame encryption.
	 * <p>
	 * Both parties derive the same TX and RX keys from the shared voice call key,
	 * but use them in opposite directions:
	 * - Alice encrypts with txKey, decrypts with rxKey
	 * - Bob encrypts with rxKey, decrypts with txKey
	 * <p>
	 * This ensures bidirectional authenticated encryption without key exchange.
	 * <p>
	 * IMPORTANT: This creates a FRESH KeyMaterialSource instance that does NOT
	 * interfere with the onion derivation KeyMaterialSource instances.
	 *
	 * @param voiceCallKey The shared voice call key
	 * @param alice True if this is Alice (caller), false if Bob (callee)
	 * @return AudioKeys containing TX key (for encryption) and RX key (for decryption)
	 */
	AudioKeys deriveAudioKeys(SecretKey voiceCallKey, boolean alice);

	/**
	 * Encrypts audio frame data using AES-256-GCM.
	 * <p>
	 * Frame format: [nonce:12][ciphertext:N][tag:16]
	 * - Nonce: 12-byte random IV for GCM mode
	 * - Ciphertext: Encrypted audio data
	 * - Tag: 16-byte authentication tag (prevents tampering)
	 *
	 * @param plaintext The raw PCM audio data
	 * @param key The encryption key (from AudioKeys.txKey)
	 * @return Encrypted frame (nonce + ciphertext + tag)
	 * @throws RuntimeException if encryption fails
	 */
	byte[] encryptAudioFrame(byte[] plaintext, SecretKey key);

	/**
	 * Decrypts audio frame data using AES-256-GCM.
	 * <p>
	 * Verifies authentication tag to detect tampering or corruption.
	 *
	 * @param ciphertext The encrypted frame (nonce + ciphertext + tag)
	 * @param key The decryption key (from AudioKeys.rxKey)
	 * @return Decrypted PCM audio data
	 * @throws RuntimeException if decryption fails or tag verification fails
	 */
	byte[] decryptAudioFrame(byte[] ciphertext, SecretKey key);

	/**
	 * Container for bidirectional audio encryption keys.
	 */
	class AudioKeys {
		/** Key for encrypting outgoing audio frames */
		public final SecretKey txKey;
		/** Key for decrypting incoming audio frames */
		public final SecretKey rxKey;

		public AudioKeys(SecretKey txKey, SecretKey rxKey) {
			this.txKey = txKey;
			this.rxKey = rxKey;
		}
	}
}
