plugins {
	id 'java-library'
	id 'com.gradleup.shadow'
}


java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

dependencies {
	implementation 'net.i2p:router:2.13.0'
	implementation 'net.i2p.client:streaming:2.13.0'
}

shadowJar {
	archiveClassifier.set('')
	relocate 'org.bouncycastle', 'org.zerionproject.i2pshaded.org.bouncycastle'
	relocate 'net.i2p.crypto.eddsa',
			'org.zerionproject.i2pshaded.net.i2p.crypto.eddsa'
	mergeServiceFiles()
}

configurations {
	shadow
}

artifacts {
	shadow(shadowJar)
}
