apply plugin: 'com.android.library'

def torBinariesDir = "$projectDir/src/main/jniLibs"

task unpackTorBinaries {
	doLast {
		configurations.releaseRuntimeClasspath.each { file ->
			if (file.name.startsWith('tor-android') || file.name.startsWith('lyrebird-android')) {
				copy {
					from zipTree(file)
					into torBinariesDir
					include '**/*.so'
				}
			}
		}
	}
}

tasks.matching { it.name == 'mergeReleaseJniLibFolders' }.configureEach {
	dependsOn unpackTorBinaries
}

tasks.matching { it.name == 'mergeDebugJniLibFolders' }.configureEach {
	dependsOn unpackTorBinaries
}

android {
	compileSdkVersion 36
	buildToolsVersion '36.0.0'
	packagingOptions {
		jniLibs {
			keepDebugSymbols += ['**/*.so']
		}
	}

	defaultConfig {
		minSdkVersion 21
		targetSdkVersion 36
		consumerProguardFiles 'proguard-rules.txt'
		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
		testInstrumentationRunnerArguments disableAnalytics: 'true'
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
	namespace 'org.zerionproject.core'
	lint {
		warning 'LintError', 'InvalidPackage', 'MissingPermission', 'InlinedApi', 'ObsoleteSdkInt', 'Override', 'NewApi', 'UnusedAttribute'
	}
}

dependencies {
	api 'org.briarproject:dont-kill-me-lib:0.2.8'
	implementation project(':bramble-api')
	implementation project(':bramble-core')
	implementation 'androidx.annotation:annotation:1.5.0'
	implementation 'net.zetetic:sqlcipher-android:4.13.0'
	implementation 'androidx.sqlite:sqlite:2.4.0'
	implementation "org.briarproject:onionwrapper-android:$onionwrapper_version"
	implementation "org.briarproject:tor-android:$tor_version"
	implementation "org.briarproject:lyrebird-android:$lyrebird_version"
	annotationProcessor "com.google.dagger:dagger-compiler:$dagger_version"
	compileOnly 'javax.annotation:jsr250-api:1.0'
	testImplementation project(path: ':bramble-api', configuration: 'testOutput')
	testImplementation "junit:junit:$junit_version"
	testImplementation "org.jmock:jmock:$jmock_version"
	testImplementation "org.jmock:jmock-junit4:$jmock_version"
	testImplementation "org.jmock:jmock-imposters:$jmock_version"
}
